### ISSUE TITLE
同学你好，请问你的加速器是挂在哪个项目实现的呢？

### ISSUE THREAD

**Issue by Crosshairs** [SingularityKChen/matrixsum#1]
是rocket-chip还是chipyard？

**Comment by SingularityKChen** [comment]
你好，这个项目没有完成，因为有的部分用的chisel2实现，有的用的chisel3，是当初学习chisel练手用的。当初是想作为RoCC，挂在chipyard下面去生成。
我最近在更新的 dl 项目就更加正规一些了，也在逐步推进。
另外要是你想要实现这个martixsum的功能，也可以在那个基础之上去更改，等我把现在的 dl 项目更新了可能会回去把这个坑补上。如果你感兴趣也可以一起协作。

**Comment by Crosshairs** [comment]
好的，谢谢。我刚开始学chipyard。
